openapi: 3.0.3
info:
  title: Open Restaurants
  description: |-
    This is a simple open restaurant service.  Find what restaurants are open by date!
    
    - [open restaurant service repository](https://github.com/marcuswu/open_restaurants)
  contact:
    email: mwu@digitaltorque.com
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/marcuswu/open_restaurants/main/LICENSE
  version: 1.0.0
servers:
  - url: https://localhost:8080/
tags:
  - name: root
    description: Find open restaurants
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /:
    get:
      tags:
        - root
      summary: Find open restaurants by date and time
      description: Provide a date (current date if not provided) and get a list of open restaurants
      operationId: findOpenRestaurantsByDate
      parameters:
        - name: date
          in: query
          description: The date in ISO-8601 format to search for open restaurants for defaults to current date
          required: false
          explode: true
          schema:
            type: string
            format: date-time
            default: current date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Invalid date value